// Generated by gencpp from file esr_msgs/Measurement.msg
// DO NOT EDIT!


#ifndef ESR_MSGS_MESSAGE_MEASUREMENT_H
#define ESR_MSGS_MESSAGE_MEASUREMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <esr_msgs/Status.h>
#include <esr_msgs/Track.h>

namespace esr_msgs
{
template <class ContainerAllocator>
struct Measurement_
{
  typedef Measurement_<ContainerAllocator> Type;

  Measurement_()
    : header()
    , status()
    , tracks()  {
    }
  Measurement_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , status(_alloc)
    , tracks(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::esr_msgs::Status_<ContainerAllocator>  _status_type;
  _status_type status;

   typedef std::vector< ::esr_msgs::Track_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::esr_msgs::Track_<ContainerAllocator> >::other >  _tracks_type;
  _tracks_type tracks;





  typedef boost::shared_ptr< ::esr_msgs::Measurement_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::esr_msgs::Measurement_<ContainerAllocator> const> ConstPtr;

}; // struct Measurement_

typedef ::esr_msgs::Measurement_<std::allocator<void> > Measurement;

typedef boost::shared_ptr< ::esr_msgs::Measurement > MeasurementPtr;
typedef boost::shared_ptr< ::esr_msgs::Measurement const> MeasurementConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::esr_msgs::Measurement_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::esr_msgs::Measurement_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace esr_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'esr_msgs': ['/home/huashuo/catkin_ws/src/Bieke/src/can/socketcan_to_topic/esr_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::esr_msgs::Measurement_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::esr_msgs::Measurement_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::esr_msgs::Measurement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::esr_msgs::Measurement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::esr_msgs::Measurement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::esr_msgs::Measurement_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::esr_msgs::Measurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1f00ed2bd4b53e883b8642a3983d0209";
  }

  static const char* value(const ::esr_msgs::Measurement_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1f00ed2bd4b53e88ULL;
  static const uint64_t static_value2 = 0x3b8642a3983d0209ULL;
};

template<class ContainerAllocator>
struct DataType< ::esr_msgs::Measurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "esr_msgs/Measurement";
  }

  static const char* value(const ::esr_msgs::Measurement_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::esr_msgs::Measurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
Status status\n\
Track[] tracks\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: esr_msgs/Status\n\
Header header\n\
# from 4e0\n\
uint16 scan_index\n\
#uint8 dsp_timestamp # in ms\n\
#float32 vehicle_speed # in m/s\n\
#float32 vehicle_yaw_rate # in in deg/s\n\
#float32 vehicle_turning_radius # in m\n\
#float32 range # cropped between 0..204.7 m\n\
bool is_comm_error\n\
# from 4e1\n\
#uint16 steering_angle_ack # in deg\n\
bool is_radiating\n\
bool is_failed\n\
bool is_blocked\n\
bool is_overheating\n\
#uint8 max_tracks_ack # 1..64\n\
bool is_raw_data_mode\n\
int8 internal_temperature # in degC\n\
uint16 sw_version\n\
#float32 yaw_rate_bias # deg/s\n\
#float32 veh_spd_comp_factor\n\
# from 4e3\n\
bool is_lr_enabled\n\
bool is_mr_enabled\n\
bool is_sidelobe_blockage\n\
bool is_partial_blockage\n\
#float32 auto_align_angle\n\
\n\
================================================================================\n\
MSG: esr_msgs/Track\n\
Header header\n\
uint8 status # 0: no target 1: new 2: new updated 3: updated 4: coasted 5: merged 6: invalid coasted 7: new coasted\n\
uint8 index # 1..64\n\
float32 range # cropped between 0..204.7 m\n\
float32 range_rate # cropped between -81.92..81.91m/s\n\
float32 range_accl # cropped between -25.6..25.55 m/s^2\n\
float32 azimuth # cropped between -51.2..51.1 deg\n\
float32 lateral_rate # cropped between -8..7.75 m/s\n\
float32 width # cropped between 0..7.5 m\n\
bool is_mr_update\n\
bool is_lr_update\n\
#bool is_oncoming\n\
#bool is_bridge\n\
#bool is_grouping_changed\n\
int8 amplitude # cropped to -10..21dB\n\
";
  }

  static const char* value(const ::esr_msgs::Measurement_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::esr_msgs::Measurement_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.status);
      stream.next(m.tracks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Measurement_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::esr_msgs::Measurement_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::esr_msgs::Measurement_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "status: ";
    s << std::endl;
    Printer< ::esr_msgs::Status_<ContainerAllocator> >::stream(s, indent + "  ", v.status);
    s << indent << "tracks[]" << std::endl;
    for (size_t i = 0; i < v.tracks.size(); ++i)
    {
      s << indent << "  tracks[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::esr_msgs::Track_<ContainerAllocator> >::stream(s, indent + "    ", v.tracks[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ESR_MSGS_MESSAGE_MEASUREMENT_H
