// Generated by gencpp from file canfd_msgs/Frame.msg
// DO NOT EDIT!


#ifndef CANFD_MSGS_MESSAGE_FRAME_H
#define CANFD_MSGS_MESSAGE_FRAME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace canfd_msgs
{
template <class ContainerAllocator>
struct Frame_
{
  typedef Frame_<ContainerAllocator> Type;

  Frame_()
    : header()
    , interface()
    , id(0)
    , is_rtr(false)
    , is_extended(false)
    , is_error(false)
    , len(0)
    , data()  {
      data.assign(0);
  }
  Frame_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , interface(_alloc)
    , id(0)
    , is_rtr(false)
    , is_extended(false)
    , is_error(false)
    , len(0)
    , data()  {
  (void)_alloc;
      data.assign(0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _interface_type;
  _interface_type interface;

   typedef uint32_t _id_type;
  _id_type id;

   typedef uint8_t _is_rtr_type;
  _is_rtr_type is_rtr;

   typedef uint8_t _is_extended_type;
  _is_extended_type is_extended;

   typedef uint8_t _is_error_type;
  _is_error_type is_error;

   typedef uint8_t _len_type;
  _len_type len;

   typedef boost::array<uint8_t, 64>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::canfd_msgs::Frame_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::canfd_msgs::Frame_<ContainerAllocator> const> ConstPtr;

}; // struct Frame_

typedef ::canfd_msgs::Frame_<std::allocator<void> > Frame;

typedef boost::shared_ptr< ::canfd_msgs::Frame > FramePtr;
typedef boost::shared_ptr< ::canfd_msgs::Frame const> FrameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::canfd_msgs::Frame_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::canfd_msgs::Frame_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace canfd_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'canfd_msgs': ['/home/huashuo/catkin_ws/src/Bieke/src/can/socketcan_to_topic/canfd_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::canfd_msgs::Frame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::canfd_msgs::Frame_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::canfd_msgs::Frame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::canfd_msgs::Frame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::canfd_msgs::Frame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::canfd_msgs::Frame_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::canfd_msgs::Frame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "67a2d3c780aad66c439e5e1657c0ce8e";
  }

  static const char* value(const ::canfd_msgs::Frame_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x67a2d3c780aad66cULL;
  static const uint64_t static_value2 = 0x439e5e1657c0ce8eULL;
};

template<class ContainerAllocator>
struct DataType< ::canfd_msgs::Frame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "canfd_msgs/Frame";
  }

  static const char* value(const ::canfd_msgs::Frame_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::canfd_msgs::Frame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
string interface\n\
uint32 id\n\
bool is_rtr\n\
bool is_extended\n\
bool is_error\n\
uint8 len\n\
uint8[64] data\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::canfd_msgs::Frame_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::canfd_msgs::Frame_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.interface);
      stream.next(m.id);
      stream.next(m.is_rtr);
      stream.next(m.is_extended);
      stream.next(m.is_error);
      stream.next(m.len);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Frame_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::canfd_msgs::Frame_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::canfd_msgs::Frame_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "interface: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.interface);
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "is_rtr: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_rtr);
    s << indent << "is_extended: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_extended);
    s << indent << "is_error: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_error);
    s << indent << "len: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.len);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CANFD_MSGS_MESSAGE_FRAME_H
